name: Man10Essentials
version: '1.0-SNAPSHOT'
main: io.github.uttmangosteen.man10Essentials.Main
api-version: '1.20'

softdepend:
  - HuskSync

commands:
  meadmin:
    usage: |
      /meadmin status
      /meadmin toggle <ec|mhat|ohatsukit|opcheck|mwhitelist>
      /meadmin set <ec|mhat|ohatsukit|opcheck|mwhitelist> <true|false>
    permission: red.man10.admin

  ec:
    permission: red.man10.ec

  mhat:
    permission: red.man10.mhat

  ohatsukit:
    usage: |
      /ohatsukit <on|off>
      /ohatsukit register
      /ohatsukit give <player>
    permission: red.man10.ohatsukit

permissions:
  red.man10.admin:
    default: op

  red.man10.ec:
    default: op

  red.man10.mhat:
    default: op

  red.man10.ohatsukit:
    default: op

  group.gm:
    default: false